// Generated by BUCKLESCRIPT VERSION 4.0.2, PLEASE EDIT WITH CARE
'use strict';

var ReactDOMRe = require("reason-react/src/ReactDOMRe.js");
var ReasonReact = require("reason-react/src/ReasonReact.js");
var PlayerExampleSong$ReasonWrapperForReactPlayer = require("./PlayerExampleSong.bs.js");

ReactDOMRe.renderToElementWithId(ReasonReact.element(undefined, undefined, PlayerExampleSong$ReasonWrapperForReactPlayer.Demo[/* make */2](/* array */[])), "body");

/*  Not a pure module */
